export interface TopicEntry {
  topic: string;
  keywords: string[];
  verses: { chapterId: number; verseNumber: number }[];
}

export const topicIndex: TopicEntry[] = [
  {
    topic: "Creation",
    keywords: ["creation", "created", "heavens", "earth", "universe", "big bang", "origin", "cosmos"],
    verses: [
      { chapterId: 2, verseNumber: 29 },
      { chapterId: 6, verseNumber: 1 },
      { chapterId: 21, verseNumber: 30 },
      { chapterId: 36, verseNumber: 36 },
      { chapterId: 41, verseNumber: 11 },
      { chapterId: 51, verseNumber: 47 },
      { chapterId: 67, verseNumber: 3 },
    ],
  },
  {
    topic: "Prayer",
    keywords: ["prayer", "salah", "salat", "worship", "prostrate", "bow", "pray", "supplication", "dua"],
    verses: [
      { chapterId: 2, verseNumber: 43 },
      { chapterId: 2, verseNumber: 238 },
      { chapterId: 4, verseNumber: 103 },
      { chapterId: 11, verseNumber: 114 },
      { chapterId: 17, verseNumber: 78 },
      { chapterId: 20, verseNumber: 14 },
      { chapterId: 29, verseNumber: 45 },
      { chapterId: 73, verseNumber: 20 },
    ],
  },
  {
    topic: "Fasting",
    keywords: ["fasting", "fast", "ramadan", "sawm", "siyam", "abstain"],
    verses: [
      { chapterId: 2, verseNumber: 183 },
      { chapterId: 2, verseNumber: 184 },
      { chapterId: 2, verseNumber: 185 },
      { chapterId: 2, verseNumber: 187 },
    ],
  },
  {
    topic: "Charity",
    keywords: ["charity", "zakat", "sadaqah", "give", "alms", "donate", "poor", "needy", "orphan", "spending"],
    verses: [
      { chapterId: 2, verseNumber: 177 },
      { chapterId: 2, verseNumber: 261 },
      { chapterId: 2, verseNumber: 267 },
      { chapterId: 2, verseNumber: 274 },
      { chapterId: 9, verseNumber: 60 },
      { chapterId: 57, verseNumber: 18 },
      { chapterId: 63, verseNumber: 10 },
      { chapterId: 107, verseNumber: 1 },
    ],
  },
  {
    topic: "Hajj and Pilgrimage",
    keywords: ["hajj", "pilgrimage", "kaaba", "mecca", "makkah", "umrah", "sacred house", "sacrifice"],
    verses: [
      { chapterId: 2, verseNumber: 196 },
      { chapterId: 2, verseNumber: 197 },
      { chapterId: 3, verseNumber: 97 },
      { chapterId: 22, verseNumber: 27 },
      { chapterId: 22, verseNumber: 28 },
      { chapterId: 22, verseNumber: 29 },
    ],
  },
  {
    topic: "Paradise and Heaven",
    keywords: ["paradise", "heaven", "jannah", "garden", "gardens", "reward", "hereafter", "eternal", "bliss"],
    verses: [
      { chapterId: 2, verseNumber: 25 },
      { chapterId: 3, verseNumber: 133 },
      { chapterId: 9, verseNumber: 72 },
      { chapterId: 13, verseNumber: 35 },
      { chapterId: 47, verseNumber: 15 },
      { chapterId: 55, verseNumber: 46 },
      { chapterId: 56, verseNumber: 10 },
      { chapterId: 76, verseNumber: 12 },
    ],
  },
  {
    topic: "Hellfire and Punishment",
    keywords: ["hell", "hellfire", "fire", "jahannam", "punishment", "torment", "doom"],
    verses: [
      { chapterId: 2, verseNumber: 24 },
      { chapterId: 3, verseNumber: 131 },
      { chapterId: 4, verseNumber: 56 },
      { chapterId: 14, verseNumber: 16 },
      { chapterId: 22, verseNumber: 19 },
      { chapterId: 67, verseNumber: 6 },
      { chapterId: 104, verseNumber: 4 },
    ],
  },
  {
    topic: "Patience and Perseverance",
    keywords: ["patience", "patient", "sabr", "persevere", "endure", "steadfast", "hardship", "trial"],
    verses: [
      { chapterId: 2, verseNumber: 45 },
      { chapterId: 2, verseNumber: 153 },
      { chapterId: 2, verseNumber: 155 },
      { chapterId: 3, verseNumber: 200 },
      { chapterId: 11, verseNumber: 115 },
      { chapterId: 16, verseNumber: 127 },
      { chapterId: 39, verseNumber: 10 },
      { chapterId: 103, verseNumber: 3 },
    ],
  },
  {
    topic: "Forgiveness and Mercy",
    keywords: ["forgiveness", "forgive", "mercy", "merciful", "pardon", "repent", "repentance", "tawbah", "compassion"],
    verses: [
      { chapterId: 2, verseNumber: 199 },
      { chapterId: 3, verseNumber: 135 },
      { chapterId: 4, verseNumber: 110 },
      { chapterId: 7, verseNumber: 156 },
      { chapterId: 39, verseNumber: 53 },
      { chapterId: 42, verseNumber: 25 },
      { chapterId: 66, verseNumber: 8 },
      { chapterId: 110, verseNumber: 3 },
    ],
  },
  {
    topic: "Justice and Fairness",
    keywords: ["justice", "just", "fair", "equity", "judge", "judgment", "rights", "oppression"],
    verses: [
      { chapterId: 4, verseNumber: 58 },
      { chapterId: 4, verseNumber: 135 },
      { chapterId: 5, verseNumber: 8 },
      { chapterId: 16, verseNumber: 90 },
      { chapterId: 49, verseNumber: 9 },
      { chapterId: 57, verseNumber: 25 },
    ],
  },
  {
    topic: "Mary and Jesus",
    keywords: ["mary", "maryam", "jesus", "isa", "messiah", "christ", "virgin", "birth"],
    verses: [
      { chapterId: 3, verseNumber: 36 },
      { chapterId: 3, verseNumber: 37 },
      { chapterId: 3, verseNumber: 42 },
      { chapterId: 3, verseNumber: 45 },
      { chapterId: 4, verseNumber: 171 },
      { chapterId: 5, verseNumber: 46 },
      { chapterId: 5, verseNumber: 110 },
      { chapterId: 19, verseNumber: 16 },
      { chapterId: 19, verseNumber: 17 },
      { chapterId: 19, verseNumber: 19 },
      { chapterId: 19, verseNumber: 22 },
      { chapterId: 19, verseNumber: 30 },
      { chapterId: 19, verseNumber: 34 },
      { chapterId: 21, verseNumber: 91 },
    ],
  },
  {
    topic: "Moses",
    keywords: ["moses", "musa", "pharaoh", "firaun", "israelites", "red sea", "staff", "tablets"],
    verses: [
      { chapterId: 2, verseNumber: 51 },
      { chapterId: 7, verseNumber: 103 },
      { chapterId: 7, verseNumber: 142 },
      { chapterId: 10, verseNumber: 75 },
      { chapterId: 20, verseNumber: 9 },
      { chapterId: 20, verseNumber: 25 },
      { chapterId: 26, verseNumber: 10 },
      { chapterId: 26, verseNumber: 63 },
      { chapterId: 28, verseNumber: 7 },
      { chapterId: 28, verseNumber: 30 },
    ],
  },
  {
    topic: "Abraham",
    keywords: ["abraham", "ibrahim", "sacrifice", "ishmael", "ismail", "hanif", "monotheism"],
    verses: [
      { chapterId: 2, verseNumber: 124 },
      { chapterId: 2, verseNumber: 127 },
      { chapterId: 2, verseNumber: 131 },
      { chapterId: 6, verseNumber: 75 },
      { chapterId: 14, verseNumber: 35 },
      { chapterId: 21, verseNumber: 69 },
      { chapterId: 37, verseNumber: 102 },
      { chapterId: 37, verseNumber: 107 },
    ],
  },
  {
    topic: "Joseph",
    keywords: ["joseph", "yusuf", "dream", "brothers", "well", "egypt", "potiphar", "prison"],
    verses: [
      { chapterId: 12, verseNumber: 3 },
      { chapterId: 12, verseNumber: 4 },
      { chapterId: 12, verseNumber: 15 },
      { chapterId: 12, verseNumber: 21 },
      { chapterId: 12, verseNumber: 46 },
      { chapterId: 12, verseNumber: 86 },
      { chapterId: 12, verseNumber: 100 },
    ],
  },
  {
    topic: "Noah",
    keywords: ["noah", "nuh", "ark", "flood", "deluge", "ship"],
    verses: [
      { chapterId: 7, verseNumber: 59 },
      { chapterId: 11, verseNumber: 36 },
      { chapterId: 11, verseNumber: 40 },
      { chapterId: 23, verseNumber: 23 },
      { chapterId: 26, verseNumber: 105 },
      { chapterId: 54, verseNumber: 9 },
      { chapterId: 71, verseNumber: 1 },
      { chapterId: 71, verseNumber: 26 },
    ],
  },
  {
    topic: "Marriage and Family",
    keywords: ["marriage", "wife", "husband", "spouse", "family", "children", "parent", "mother", "father", "wedding"],
    verses: [
      { chapterId: 2, verseNumber: 221 },
      { chapterId: 2, verseNumber: 228 },
      { chapterId: 4, verseNumber: 1 },
      { chapterId: 4, verseNumber: 19 },
      { chapterId: 4, verseNumber: 34 },
      { chapterId: 17, verseNumber: 23 },
      { chapterId: 25, verseNumber: 74 },
      { chapterId: 30, verseNumber: 21 },
      { chapterId: 31, verseNumber: 14 },
      { chapterId: 46, verseNumber: 15 },
    ],
  },
  {
    topic: "Death and Afterlife",
    keywords: ["death", "die", "resurrection", "judgment day", "qiyamah", "grave", "soul", "afterlife", "hereafter"],
    verses: [
      { chapterId: 2, verseNumber: 28 },
      { chapterId: 3, verseNumber: 185 },
      { chapterId: 6, verseNumber: 60 },
      { chapterId: 21, verseNumber: 35 },
      { chapterId: 23, verseNumber: 99 },
      { chapterId: 29, verseNumber: 57 },
      { chapterId: 39, verseNumber: 42 },
      { chapterId: 50, verseNumber: 19 },
      { chapterId: 75, verseNumber: 1 },
    ],
  },
  {
    topic: "Trust in God",
    keywords: ["trust", "tawakkul", "reliance", "depend", "god's plan", "decree", "qadr", "fate", "destiny"],
    verses: [
      { chapterId: 3, verseNumber: 159 },
      { chapterId: 8, verseNumber: 2 },
      { chapterId: 9, verseNumber: 51 },
      { chapterId: 12, verseNumber: 67 },
      { chapterId: 14, verseNumber: 12 },
      { chapterId: 33, verseNumber: 3 },
      { chapterId: 65, verseNumber: 3 },
    ],
  },
  {
    topic: "Gratitude and Thankfulness",
    keywords: ["grateful", "gratitude", "thankful", "thanks", "shukr", "blessings", "praise", "alhamdulillah"],
    verses: [
      { chapterId: 2, verseNumber: 152 },
      { chapterId: 14, verseNumber: 7 },
      { chapterId: 16, verseNumber: 114 },
      { chapterId: 27, verseNumber: 40 },
      { chapterId: 31, verseNumber: 12 },
      { chapterId: 34, verseNumber: 13 },
      { chapterId: 55, verseNumber: 13 },
    ],
  },
  {
    topic: "Knowledge and Wisdom",
    keywords: ["knowledge", "learn", "wisdom", "understand", "intellect", "reflect", "think", "ponder", "science", "read"],
    verses: [
      { chapterId: 2, verseNumber: 269 },
      { chapterId: 3, verseNumber: 190 },
      { chapterId: 20, verseNumber: 114 },
      { chapterId: 35, verseNumber: 28 },
      { chapterId: 39, verseNumber: 9 },
      { chapterId: 58, verseNumber: 11 },
      { chapterId: 96, verseNumber: 1 },
      { chapterId: 96, verseNumber: 4 },
    ],
  },
  {
    topic: "Monotheism and Oneness of God",
    keywords: ["one god", "tawhid", "monotheism", "oneness", "no god but", "la ilaha", "unity", "shirk", "polytheism", "idol"],
    verses: [
      { chapterId: 2, verseNumber: 163 },
      { chapterId: 2, verseNumber: 255 },
      { chapterId: 3, verseNumber: 18 },
      { chapterId: 4, verseNumber: 36 },
      { chapterId: 6, verseNumber: 102 },
      { chapterId: 21, verseNumber: 25 },
      { chapterId: 23, verseNumber: 91 },
      { chapterId: 112, verseNumber: 1 },
      { chapterId: 112, verseNumber: 2 },
      { chapterId: 112, verseNumber: 3 },
      { chapterId: 112, verseNumber: 4 },
    ],
  },
  {
    topic: "Angels",
    keywords: ["angel", "angels", "jibril", "gabriel", "mika'il", "michael", "israfil", "angel of death"],
    verses: [
      { chapterId: 2, verseNumber: 30 },
      { chapterId: 2, verseNumber: 98 },
      { chapterId: 2, verseNumber: 177 },
      { chapterId: 16, verseNumber: 2 },
      { chapterId: 35, verseNumber: 1 },
      { chapterId: 53, verseNumber: 5 },
      { chapterId: 66, verseNumber: 6 },
      { chapterId: 97, verseNumber: 4 },
    ],
  },
  {
    topic: "Satan and Evil",
    keywords: ["satan", "shaytan", "iblis", "devil", "evil", "whisper", "jinn", "temptation"],
    verses: [
      { chapterId: 2, verseNumber: 34 },
      { chapterId: 2, verseNumber: 36 },
      { chapterId: 4, verseNumber: 76 },
      { chapterId: 7, verseNumber: 11 },
      { chapterId: 7, verseNumber: 16 },
      { chapterId: 15, verseNumber: 34 },
      { chapterId: 36, verseNumber: 60 },
      { chapterId: 114, verseNumber: 4 },
      { chapterId: 114, verseNumber: 5 },
    ],
  },
  {
    topic: "Day of Judgment",
    keywords: ["day of judgment", "last day", "yawm al-qiyamah", "hour", "reckoning", "trumpet", "scales", "accounting"],
    verses: [
      { chapterId: 1, verseNumber: 4 },
      { chapterId: 7, verseNumber: 187 },
      { chapterId: 21, verseNumber: 47 },
      { chapterId: 22, verseNumber: 1 },
      { chapterId: 39, verseNumber: 68 },
      { chapterId: 69, verseNumber: 13 },
      { chapterId: 78, verseNumber: 17 },
      { chapterId: 81, verseNumber: 1 },
      { chapterId: 82, verseNumber: 1 },
      { chapterId: 99, verseNumber: 1 },
    ],
  },
  {
    topic: "Quran and Revelation",
    keywords: ["quran", "book", "revelation", "recite", "scripture", "verse", "sign", "guidance", "light", "furqan"],
    verses: [
      { chapterId: 2, verseNumber: 2 },
      { chapterId: 2, verseNumber: 185 },
      { chapterId: 4, verseNumber: 82 },
      { chapterId: 6, verseNumber: 19 },
      { chapterId: 15, verseNumber: 9 },
      { chapterId: 17, verseNumber: 9 },
      { chapterId: 25, verseNumber: 1 },
      { chapterId: 36, verseNumber: 2 },
      { chapterId: 56, verseNumber: 77 },
    ],
  },
  {
    topic: "Water and Rain",
    keywords: ["water", "rain", "river", "sea", "ocean", "spring", "drink", "flood"],
    verses: [
      { chapterId: 2, verseNumber: 22 },
      { chapterId: 6, verseNumber: 99 },
      { chapterId: 16, verseNumber: 65 },
      { chapterId: 21, verseNumber: 30 },
      { chapterId: 23, verseNumber: 18 },
      { chapterId: 24, verseNumber: 43 },
      { chapterId: 25, verseNumber: 48 },
      { chapterId: 56, verseNumber: 68 },
    ],
  },
  {
    topic: "Light and Darkness",
    keywords: ["light", "darkness", "nur", "lamp", "sun", "moon", "star", "illuminate"],
    verses: [
      { chapterId: 6, verseNumber: 1 },
      { chapterId: 24, verseNumber: 35 },
      { chapterId: 33, verseNumber: 43 },
      { chapterId: 35, verseNumber: 20 },
      { chapterId: 57, verseNumber: 12 },
      { chapterId: 71, verseNumber: 16 },
    ],
  },
  {
    topic: "Honesty and Truthfulness",
    keywords: ["honest", "truth", "truthful", "lie", "lying", "sincere", "sincerity", "trustworthy", "deceit"],
    verses: [
      { chapterId: 2, verseNumber: 42 },
      { chapterId: 3, verseNumber: 17 },
      { chapterId: 9, verseNumber: 119 },
      { chapterId: 17, verseNumber: 36 },
      { chapterId: 33, verseNumber: 70 },
      { chapterId: 49, verseNumber: 6 },
    ],
  },
  {
    topic: "Modesty and Hijab",
    keywords: ["modesty", "hijab", "cover", "veil", "lower gaze", "dress", "modest", "clothing"],
    verses: [
      { chapterId: 24, verseNumber: 30 },
      { chapterId: 24, verseNumber: 31 },
      { chapterId: 33, verseNumber: 53 },
      { chapterId: 33, verseNumber: 59 },
    ],
  },
  {
    topic: "Food and Dietary Laws",
    keywords: ["food", "halal", "haram", "eat", "drink", "pork", "alcohol", "wine", "meat", "slaughter"],
    verses: [
      { chapterId: 2, verseNumber: 168 },
      { chapterId: 2, verseNumber: 173 },
      { chapterId: 5, verseNumber: 3 },
      { chapterId: 5, verseNumber: 90 },
      { chapterId: 6, verseNumber: 145 },
      { chapterId: 16, verseNumber: 114 },
    ],
  },
  {
    topic: "Wealth and Materialism",
    keywords: ["wealth", "money", "rich", "poverty", "worldly", "dunya", "greed", "materialism", "provision"],
    verses: [
      { chapterId: 2, verseNumber: 188 },
      { chapterId: 3, verseNumber: 14 },
      { chapterId: 4, verseNumber: 29 },
      { chapterId: 9, verseNumber: 34 },
      { chapterId: 18, verseNumber: 46 },
      { chapterId: 57, verseNumber: 20 },
      { chapterId: 89, verseNumber: 20 },
      { chapterId: 102, verseNumber: 1 },
    ],
  },
  {
    topic: "Kindness to Parents",
    keywords: ["parents", "mother", "father", "obedience", "kindness", "birr", "elderly", "respect"],
    verses: [
      { chapterId: 2, verseNumber: 83 },
      { chapterId: 4, verseNumber: 36 },
      { chapterId: 6, verseNumber: 151 },
      { chapterId: 17, verseNumber: 23 },
      { chapterId: 17, verseNumber: 24 },
      { chapterId: 29, verseNumber: 8 },
      { chapterId: 31, verseNumber: 14 },
      { chapterId: 46, verseNumber: 15 },
    ],
  },
  {
    topic: "Nature and Environment",
    keywords: ["nature", "environment", "animal", "plant", "tree", "mountain", "sky", "bee", "ant", "bird"],
    verses: [
      { chapterId: 6, verseNumber: 38 },
      { chapterId: 13, verseNumber: 3 },
      { chapterId: 16, verseNumber: 68 },
      { chapterId: 24, verseNumber: 41 },
      { chapterId: 27, verseNumber: 18 },
      { chapterId: 30, verseNumber: 41 },
      { chapterId: 55, verseNumber: 6 },
    ],
  },
  {
    topic: "Peace and Greeting",
    keywords: ["peace", "salam", "greeting", "harmony", "reconciliation", "tranquility"],
    verses: [
      { chapterId: 4, verseNumber: 86 },
      { chapterId: 6, verseNumber: 54 },
      { chapterId: 10, verseNumber: 25 },
      { chapterId: 25, verseNumber: 63 },
      { chapterId: 36, verseNumber: 58 },
      { chapterId: 56, verseNumber: 26 },
      { chapterId: 97, verseNumber: 5 },
    ],
  },
  {
    topic: "Muhammad the Prophet",
    keywords: ["muhammad", "prophet", "messenger", "rasul", "seal of prophets", "ahmad"],
    verses: [
      { chapterId: 3, verseNumber: 144 },
      { chapterId: 33, verseNumber: 21 },
      { chapterId: 33, verseNumber: 40 },
      { chapterId: 33, verseNumber: 56 },
      { chapterId: 47, verseNumber: 2 },
      { chapterId: 48, verseNumber: 29 },
      { chapterId: 61, verseNumber: 6 },
      { chapterId: 68, verseNumber: 4 },
    ],
  },
  {
    topic: "David and Solomon",
    keywords: ["david", "dawud", "solomon", "sulaiman", "psalms", "zabur", "kingdom", "wind"],
    verses: [
      { chapterId: 2, verseNumber: 251 },
      { chapterId: 21, verseNumber: 78 },
      { chapterId: 21, verseNumber: 79 },
      { chapterId: 27, verseNumber: 15 },
      { chapterId: 27, verseNumber: 16 },
      { chapterId: 34, verseNumber: 10 },
      { chapterId: 34, verseNumber: 12 },
      { chapterId: 38, verseNumber: 18 },
      { chapterId: 38, verseNumber: 30 },
    ],
  },
  {
    topic: "Love",
    keywords: ["love", "beloved", "affection", "compassion", "hubb", "mawaddah"],
    verses: [
      { chapterId: 2, verseNumber: 165 },
      { chapterId: 3, verseNumber: 14 },
      { chapterId: 3, verseNumber: 31 },
      { chapterId: 5, verseNumber: 54 },
      { chapterId: 19, verseNumber: 96 },
      { chapterId: 30, verseNumber: 21 },
      { chapterId: 85, verseNumber: 14 },
    ],
  },
  {
    topic: "Fear and Hope",
    keywords: ["fear", "hope", "taqwa", "god-fearing", "piety", "awe", "conscious", "afraid"],
    verses: [
      { chapterId: 2, verseNumber: 218 },
      { chapterId: 3, verseNumber: 175 },
      { chapterId: 7, verseNumber: 56 },
      { chapterId: 15, verseNumber: 49 },
      { chapterId: 32, verseNumber: 16 },
      { chapterId: 39, verseNumber: 9 },
      { chapterId: 59, verseNumber: 18 },
    ],
  },
  {
    topic: "Embryology and Human Development",
    keywords: ["embryo", "womb", "clot", "sperm", "fetus", "stages", "bone", "flesh", "human development"],
    verses: [
      { chapterId: 22, verseNumber: 5 },
      { chapterId: 23, verseNumber: 12 },
      { chapterId: 23, verseNumber: 13 },
      { chapterId: 23, verseNumber: 14 },
      { chapterId: 39, verseNumber: 6 },
      { chapterId: 75, verseNumber: 37 },
      { chapterId: 76, verseNumber: 2 },
      { chapterId: 96, verseNumber: 2 },
    ],
  },
  {
    topic: "Inheritance",
    keywords: ["inheritance", "will", "heir", "estate", "share", "bequest"],
    verses: [
      { chapterId: 2, verseNumber: 180 },
      { chapterId: 4, verseNumber: 7 },
      { chapterId: 4, verseNumber: 11 },
      { chapterId: 4, verseNumber: 12 },
      { chapterId: 4, verseNumber: 176 },
    ],
  },
  {
    topic: "Usury and Interest",
    keywords: ["usury", "interest", "riba", "loan", "debt", "banking"],
    verses: [
      { chapterId: 2, verseNumber: 275 },
      { chapterId: 2, verseNumber: 276 },
      { chapterId: 2, verseNumber: 278 },
      { chapterId: 3, verseNumber: 130 },
      { chapterId: 4, verseNumber: 161 },
      { chapterId: 30, verseNumber: 39 },
    ],
  },
  {
    topic: "War and Jihad",
    keywords: ["war", "jihad", "fight", "battle", "struggle", "defense", "combat", "martyr"],
    verses: [
      { chapterId: 2, verseNumber: 190 },
      { chapterId: 2, verseNumber: 216 },
      { chapterId: 4, verseNumber: 74 },
      { chapterId: 8, verseNumber: 60 },
      { chapterId: 9, verseNumber: 20 },
      { chapterId: 22, verseNumber: 39 },
      { chapterId: 49, verseNumber: 15 },
    ],
  },
  {
    topic: "Brotherhood and Unity",
    keywords: ["brother", "brotherhood", "unity", "ummah", "community", "together", "hold fast"],
    verses: [
      { chapterId: 3, verseNumber: 103 },
      { chapterId: 8, verseNumber: 63 },
      { chapterId: 21, verseNumber: 92 },
      { chapterId: 49, verseNumber: 10 },
      { chapterId: 49, verseNumber: 13 },
      { chapterId: 61, verseNumber: 4 },
    ],
  },
  {
    topic: "Backbiting and Gossip",
    keywords: ["backbiting", "gossip", "slander", "spy", "suspicion", "rumor", "mock"],
    verses: [
      { chapterId: 24, verseNumber: 19 },
      { chapterId: 49, verseNumber: 11 },
      { chapterId: 49, verseNumber: 12 },
      { chapterId: 68, verseNumber: 11 },
      { chapterId: 104, verseNumber: 1 },
    ],
  },
  {
    topic: "Ayat al-Kursi",
    keywords: ["ayat al-kursi", "throne verse", "kursi", "chair", "no slumber"],
    verses: [
      { chapterId: 2, verseNumber: 255 },
    ],
  },
  {
    topic: "Surah Al-Fatiha",
    keywords: ["fatiha", "opening", "opener", "guide us", "straight path"],
    verses: [
      { chapterId: 1, verseNumber: 1 },
      { chapterId: 1, verseNumber: 2 },
      { chapterId: 1, verseNumber: 3 },
      { chapterId: 1, verseNumber: 4 },
      { chapterId: 1, verseNumber: 5 },
      { chapterId: 1, verseNumber: 6 },
      { chapterId: 1, verseNumber: 7 },
    ],
  },
  {
    topic: "Night and Stars",
    keywords: ["night", "star", "stars", "constellation", "sky", "space", "orbit", "sunrise", "sunset"],
    verses: [
      { chapterId: 6, verseNumber: 97 },
      { chapterId: 16, verseNumber: 16 },
      { chapterId: 36, verseNumber: 37 },
      { chapterId: 36, verseNumber: 38 },
      { chapterId: 36, verseNumber: 40 },
      { chapterId: 51, verseNumber: 7 },
      { chapterId: 53, verseNumber: 1 },
      { chapterId: 81, verseNumber: 15 },
      { chapterId: 86, verseNumber: 1 },
    ],
  },
  {
    topic: "Surah Yaseen",
    keywords: ["yaseen", "yasin", "ya sin", "heart of quran"],
    verses: [
      { chapterId: 36, verseNumber: 1 },
      { chapterId: 36, verseNumber: 2 },
      { chapterId: 36, verseNumber: 3 },
    ],
  },
  {
    topic: "Protection and Refuge",
    keywords: ["protection", "refuge", "seek refuge", "auzu", "evil eye", "jealousy", "envy", "morning", "evening"],
    verses: [
      { chapterId: 2, verseNumber: 255 },
      { chapterId: 113, verseNumber: 1 },
      { chapterId: 113, verseNumber: 2 },
      { chapterId: 113, verseNumber: 3 },
      { chapterId: 113, verseNumber: 4 },
      { chapterId: 113, verseNumber: 5 },
      { chapterId: 114, verseNumber: 1 },
      { chapterId: 114, verseNumber: 2 },
      { chapterId: 114, verseNumber: 3 },
      { chapterId: 114, verseNumber: 4 },
      { chapterId: 114, verseNumber: 5 },
      { chapterId: 114, verseNumber: 6 },
    ],
  },
  {
    topic: "Hypocrisy",
    keywords: ["hypocrite", "hypocrisy", "munafiq", "pretend", "two-faced", "deceive believers"],
    verses: [
      { chapterId: 2, verseNumber: 8 },
      { chapterId: 2, verseNumber: 14 },
      { chapterId: 4, verseNumber: 142 },
      { chapterId: 9, verseNumber: 67 },
      { chapterId: 33, verseNumber: 1 },
      { chapterId: 63, verseNumber: 1 },
      { chapterId: 63, verseNumber: 4 },
    ],
  },
  {
    topic: "Miracles and Signs",
    keywords: ["miracle", "sign", "proof", "wonder", "evidence", "ayah"],
    verses: [
      { chapterId: 2, verseNumber: 164 },
      { chapterId: 3, verseNumber: 49 },
      { chapterId: 6, verseNumber: 95 },
      { chapterId: 10, verseNumber: 5 },
      { chapterId: 16, verseNumber: 12 },
      { chapterId: 30, verseNumber: 20 },
      { chapterId: 41, verseNumber: 53 },
      { chapterId: 45, verseNumber: 3 },
    ],
  },
  {
    topic: "Supplication (Dua)",
    keywords: ["dua", "supplication", "call upon", "invoke", "ask", "beseech", "prayer request"],
    verses: [
      { chapterId: 2, verseNumber: 186 },
      { chapterId: 7, verseNumber: 55 },
      { chapterId: 7, verseNumber: 56 },
      { chapterId: 14, verseNumber: 40 },
      { chapterId: 25, verseNumber: 77 },
      { chapterId: 27, verseNumber: 62 },
      { chapterId: 40, verseNumber: 60 },
    ],
  },
  {
    topic: "Prophets and Messengers",
    keywords: ["prophet", "messenger", "sent", "nabi", "rasool", "apostle"],
    verses: [
      { chapterId: 2, verseNumber: 136 },
      { chapterId: 2, verseNumber: 285 },
      { chapterId: 3, verseNumber: 81 },
      { chapterId: 4, verseNumber: 163 },
      { chapterId: 6, verseNumber: 84 },
      { chapterId: 21, verseNumber: 25 },
      { chapterId: 33, verseNumber: 7 },
    ],
  },
];

export function searchTopicIndex(query: string): { chapterId: number; verseNumber: number; topic: string }[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  const results: { chapterId: number; verseNumber: number; topic: string }[] = [];
  const seen = new Set<string>();

  for (const entry of topicIndex) {
    const topicMatch = entry.topic.toLowerCase().includes(q);
    const keywordMatch = entry.keywords.some((kw) => kw.includes(q) || q.includes(kw));

    if (topicMatch || keywordMatch) {
      for (const v of entry.verses) {
        const key = `${v.chapterId}:${v.verseNumber}`;
        if (!seen.has(key)) {
          seen.add(key);
          results.push({ ...v, topic: entry.topic });
        }
      }
    }
  }

  return results;
}
