import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

// Prepends a synthetic verse-0 Bismillah entry to every surah's local verse
// data, except:
//   - Surah 1 (Al-Fatiha): the Bismillah is already its real verse 1.
//   - Surah 9 (At-Tawbah): the Bismillah is not recited/written there.
//
// Source of truth is client/public/data/chapters/*.json — this is what the
// running app fetches (dev via Vite middleware, prod via `vite build` which
// copies client/public into dist/public, which Express serves). dist/public
// is a build artifact regenerated by `npm run build`; the iOS/Android bundled
// copies are regenerated by `npx cap sync` from dist/public. Neither should
// be hand-edited — see scripts/README notes / task report for details.
//
// Idempotent: safe to re-run, skips chapters that already have a verse 0.

const chaptersDir = join(process.cwd(), 'client/public/data/chapters');

interface LocalVerse {
  number: number;
  arabicText: string;
  transliteration: string;
  translation: string;
}

interface ChapterData {
  id: number;
  verses: LocalVerse[];
}

// Derive the exact Bismillah string from Surah 1's own verse 1, so the
// synthetic verse-0 entries are byte-for-byte identical to how the phrase is
// already represented in this same dataset.
const fatiha: ChapterData = JSON.parse(
  readFileSync(join(chaptersDir, '1.json'), 'utf-8'),
);
const fatihaVerse1 = fatiha.verses.find((v) => v.number === 1);
if (!fatihaVerse1) {
  throw new Error('Could not find verse 1 in chapter 1.json to source the Bismillah text from');
}

const bismillah: LocalVerse = {
  number: 0,
  arabicText: fatihaVerse1.arabicText,
  transliteration: fatihaVerse1.transliteration,
  translation: fatihaVerse1.translation,
};

console.log('Using Bismillah text:');
console.log(`  arabicText:      ${JSON.stringify(bismillah.arabicText)}`);
console.log(`  transliteration: ${JSON.stringify(bismillah.transliteration)}`);
console.log(`  translation:     ${JSON.stringify(bismillah.translation)}`);
console.log('');

let added = 0;
let skippedAlreadyPresent = 0;

for (let i = 1; i <= 114; i++) {
  if (i === 1 || i === 9) {
    continue; // Al-Fatiha and At-Tawbah are excluded.
  }

  const filePath = join(chaptersDir, `${i}.json`);
  const data: ChapterData = JSON.parse(readFileSync(filePath, 'utf-8'));

  if (data.verses[0]?.number === 0) {
    skippedAlreadyPresent++;
    continue;
  }

  data.verses.unshift({ ...bismillah });
  writeFileSync(filePath, JSON.stringify(data));
  added++;
}

console.log(`Added Bismillah preamble to ${added} chapters.`);
console.log(`Skipped ${skippedAlreadyPresent} chapters (already had a verse 0).`);
console.log('Chapters 1 and 9 were left untouched.');
